//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Calculadora.java
//  @ Date : 20/08/2021
//  @ Author : Jorge Rodrigo Gómez Mayo
//
//




public class Calculadora {
   //Variables de instancia
	private String marca;
	private String modelo;
	private double memoria;
   //Constructor
	public Calculadora(String marca, String modelo, double memoria) {
	this.marca=marca;
   this.modelo=modelo;
   this.memoria=memoria;
	}
   //Método multiplicar
	public void sumar() {
	
	}
	//Método multiplicar
	public void multiplicar() {
	
	}
}

class Principal{
   //Método main
   public static void main (String arg[]){
   Calculadora calculadora1=new Calculadora("Casio", "fx-3", 1064);
   }
}
