//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Estudiante.java
//  @ Date : 24/08/2021
//  @ Author : Jorge Rodrigo Gómez Mayo



//Clase Estudiante
public class Estudiante {
   //Atributos
	private int matricula;
	private float cal1;
	private float cal2;
	private float cal3;
   //Constructor
	public Estudiante(int matricula, float cal1, float cal2, float cal3) {
	this.matricula=matricula;
   this.cal1=cal1;
   this.cal2=cal2;
   this.cal3=cal3;
	}
	//Método para calcular el promedio
	public double calPromedio() {
	return (cal1+cal2+cal3)/3;
	}
	//Método para desplegar el resultado
	public String toString() {
	return "Matricula: "+matricula+"\tpromedio: "+calPromedio();
	}
}

class Principal{
   public static void main(String arg[]){
   Estudiante e1=new Estudiante(612473, 99.9f, 89.5f, 78.8f);
   System.out.println(e1);
   
   Estudiante e2=new Estudiante(732461, 99.9f, 89.5f, 78.8f);
   System.out.println(e2);
   }
}