//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Fraccion.java
//  @ Date : 24/08/2021
//  @ Author : Jorge Rodrigo Gómez Mayo


import java.io.*; //Este se usa para los sytem in y out
import java.util.*; //Para el scanner

//Clase Fracción
public class Fraccion {
   //Atributos
	private double n1;
	private double d1;
   //Constructor
	public Fraccion(double n1, double d1) {
	setNumerador(n1);
   setDenominador(d1);
	}
   
   //Método set para el numerador
   public void setNumerador(double n1) {
   this.n1=n1;
   }
   //Método set para el denomindador
   public void setDenominador(double d1) {
   this.d1=d1;
   }
   //Método get para el numerador
   public double getNumerador() {
   return n1;
   }
   //Método get para el denominador
   public double getDenominador() {
   return d1;
   }
   
	//Método para hacer la división
	public double dividir() {
	return n1/d1;
	}
	//Método para desplegar el resultado
	public String toString() {
	return "La fracción "+n1+"/"+d1+" es igual a: "+dividir();
	}
}

//Clase main
class Principal{
   public static void main(String arg[]){
    double numerador=guardarNumerador();
    double denominador=guardarDenominador();
    Fraccion f1=new Fraccion (numerador, denominador);
    System.out.println("El numerador es: "+f1.getNumerador());
    System.out.println("El denominadorr es: "+f1.getDenominador());
    System.out.println(f1);
   }
  //Método para guardar al numerador
  public static double guardarNumerador(){
    Scanner s=new Scanner (System.in);
    System.out.println("Ingresa el numerador: ");
    double numerador=s.nextDouble();
    return numerador;
  }
  //Método para guardar al denominador
  public static double guardarDenominador(){
    double denominador=0;
    while (denominador==0){//Mientras no se introduzca un valor diferente a 0, se cicla
      System.out.println("El denominador no puede ser 0");
      Scanner s=new Scanner (System.in);
      System.out.println("Ingresa el denominador: ");
      denominador=s.nextDouble();
    }
    return denominador;
  }
}