//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Humano.java
//  @ Date : 27/08/2021
//  @ Author : Jorge Rodrigo Gómez Mayo


import java.io.*; //Este se usa para los sytem in y out
import java.util.*; //Para el scanner

//Clase Humano
public class Humano {
   //Atributos
   private String nombre;
	private float altura;
	private float masa;
	private char sexo;
   //Constructor
	public Humano(String nombre, float altura, float masa, char sexo) {
   this.nombre=nombre;
	this.altura=altura;
   this.masa=masa;
   this.sexo=sexo;
	}
	
   //Método para calcular la masa corporal
	public float calMasaCorporal() {
   float imc=Math.round((masa/(altura*altura))*10); //Usamos Math.round para redondearlo y quitarle decimales 
	return imc/10;
	}
   //Método para calcular la masa ideal de los hombres
	public float calMasaIdealH() {
	return Math.round((altura%1)*100); //Usamos Math.round para dar la respuesta como un entero y eliminar los decimales que daban .000001 o .9999999
	}
   //Método para calcular la masa ideal de las mujeres
	public float calMasaIdealM() {
	return Math.round(((altura%1)*100)-10); //Usamos Math.round para dar la respuesta como un entero y eliminar los decimales que daban .000001 o .9999999
	}
   //Método para desplegar el resultado
	public String toString() {
   String mensaje="";
   switch(sexo){ //Usamos un switch, que según el sexo genera el mensaje correspondiente.
      case 'H': mensaje= "Nombre: "+nombre+"\tIMC: "+calMasaCorporal()+"\tMasa Ideal: "+calMasaIdealH(); //Mensaje usando la formula para los hombres
      break; 
      case 'M': mensaje= "Nombre: "+nombre+"\tIMC: "+calMasaCorporal()+"\tMasa Ideal: "+calMasaIdealM(); //Mensaje usando la formula para las mujeres
      break; 
      }
      return mensaje;
	}
   
}

//Clase Principal
class Principal{ //Aquí va todo lo que hara el programa
   public static void main(String arg[]){
   boolean acceso=validarAcceso();
   String nombre=guardarNombre();
   float altura=guardarAltura();
   float masa=guardarMasa();
   char sexo=guardarSexo();
   Humano h1=new Humano (nombre, altura, masa, sexo); //Creamos al objeto con los datos que se ingresan
   System.out.println(h1);
   }
  
  //Método para ingresar el usuario y la contraseña válida
  public static boolean validarAcceso(){
    boolean validar=false;
    String usuario="Usuario1";
    String contrasena="Admin12!";
    while (validar!=true){
      Scanner s=new Scanner (System.in);
      System.out.print("Usuario: ");
      String intentoUsuario=s.nextLine();
      System.out.println("Contrasena: ");
      String intentoContrasena=s.nextLine();
      if (intentoUsuario.equals(usuario) && intentoContrasena.equals(contrasena)){
       validar=true;
      }
      else{
       System.out.println("Usuario y/o contrasena incorrecta(s).\nIntente de nuevo.\n");
      }
    }
    return true;
  } 
  //Método para guardar el nombre
  public static String guardarNombre(){
    Scanner s=new Scanner (System.in);
    System.out.println("Ingresa el nombre: ");
    String nombre=s.next();
    return nombre;
  }
  //Método para guardar la altura
  public static float guardarAltura(){
    Scanner s=new Scanner (System.in);
    System.out.println("Ingresa la altura en metros: ");
    float altura=s.nextFloat();
    return altura;
  }
  //Método para guardar la masa
  public static float guardarMasa(){
    Scanner s=new Scanner (System.in);
    System.out.println("Ingresa la masa en kilogramos: ");
    float masa=s.nextFloat();
    return masa;
  }
  //Método para guardar el sexo
  public static char guardarSexo(){
    boolean validar=false;
    char sexoV=' ';
    while (validar!=true){ //Mientras validar no sea 1 nos quedamos en el loop
      Scanner s=new Scanner (System.in);
      System.out.println("Ingresa 'H' para Hombre o 'M' para Mujer: ");
      String stringSexo=s.next();
      stringSexo=stringSexo.toUpperCase(); //convertimos a mayúsculas para que no sea tan cuadrada la validación
      if ((stringSexo.charAt(0)=='H' || stringSexo.charAt(0)=='M') && stringSexo.length()==1){ //si la letra es H o M  y solo se ingreso un cáracter, cambiamos el valor de validar a 1 y guardamos el valor que queremos regresar
       validar=true;
       sexoV=stringSexo.charAt(0);
       }
      else{
       System.out.println("Valor invalido!\nPor favor ingresa 'H' o 'M'\n");
       }
      }
    return sexoV;
  }
  
}